# NOTE: Generated By HttpRunner v3.1.6
# FROM: har/login.har


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCaseLogin(HttpRunner):

    config = Config("testcase description").verify(False)

    teststeps = [
        Step(
            RunRequest("/v1/user/login")
            .post("http://10.4.12.64:30007/v1/user/login")
            .with_headers(
                **{
                    "Host": "10.4.12.64:30007",
                    "Connection": "keep-alive",
                    "Content-Length": "44",
                    "Accept": "application/json, text/plain, */*",
                    "Pragma": "no-cache",
                    "Cache-Control": "no-cache",
                    "language": "en",
                    "Content-Type": "application/json;charset=UTF-8",
                    "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.54 Safari/537.36",
                    "Expires": "-1",
                    "Origin": "http://10.4.12.64:30007",
                    "Referer": "http://10.4.12.64:30007/login",
                    "Accept-Encoding": "gzip, deflate",
                    "Accept-Language": "zh-CN,zh;q=0.9,en-US;q=0.8,en;q=0.7",
                }
            )
            .with_json({"user": "admin2021", "password": "Admin@2021"})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal('headers."Content-Type"', "application/json")
            .assert_equal("body.code", 0)
            .assert_equal("body.msg", "success")
            .assert_equal("body.data.id", 1)
        ),
        Step(
            RunRequest("/v1/net/get_net_list")
            .get("http://10.4.12.64:30007/v1/net/get_net_list")
            .with_headers(
                **{
                    "Host": "10.4.12.64:30007",
                    "Connection": "keep-alive",
                    "Pragma": "no-cache",
                    "language": "en",
                    "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.54 Safari/537.36",
                    "Content-Type": "application/json;charset=utf-8",
                    "Accept": "application/json, text/plain, */*",
                    "Cache-Control": "no-cache",
                    "token": "industry-qa-accessToken=705d3309128d1981312286760cb0488b",
                    "Expires": "-1",
                    "Referer": "http://10.4.12.64:30007/system/networksetup",
                    "Accept-Encoding": "gzip, deflate",
                    "Accept-Language": "zh-CN,zh;q=0.9,en-US;q=0.8,en;q=0.7",
                    "Cookie": "industry-qa-accessToken=industry-qa-accessToken=705d3309128d1981312286760cb0488b",
                }
            )
            .with_cookies(
                **{
                    "industry-qa-accessToken": "industry-qa-accessToken=705d3309128d1981312286760cb0488b"
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal('headers."Content-Type"', "application/json")
            .assert_equal("body.code", 0)
            .assert_equal("body.msg", "success")
        ),
        Step(
            RunRequest("/v1/dns/get_dns")
            .get("http://10.4.12.64:30007/v1/dns/get_dns")
            .with_headers(
                **{
                    "Host": "10.4.12.64:30007",
                    "Connection": "keep-alive",
                    "Pragma": "no-cache",
                    "language": "en",
                    "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.54 Safari/537.36",
                    "Content-Type": "application/json;charset=utf-8",
                    "Accept": "application/json, text/plain, */*",
                    "Cache-Control": "no-cache",
                    "token": "industry-qa-accessToken=705d3309128d1981312286760cb0488b",
                    "Expires": "-1",
                    "Referer": "http://10.4.12.64:30007/system/networksetup",
                    "Accept-Encoding": "gzip, deflate",
                    "Accept-Language": "zh-CN,zh;q=0.9,en-US;q=0.8,en;q=0.7",
                    "Cookie": "industry-qa-accessToken=industry-qa-accessToken=705d3309128d1981312286760cb0488b",
                }
            )
            .with_cookies(
                **{
                    "industry-qa-accessToken": "industry-qa-accessToken=705d3309128d1981312286760cb0488b"
                }
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal('headers."Content-Type"', "application/json")
            .assert_equal("body.code", 0)
            .assert_equal("body.msg", "success")
        ),
    ]


if __name__ == "__main__":
    TestCaseLogin().test_start()
